export const ELECTORAL_VOTES_BY_STATE: Record<string, number> = {
  AL: 9,
  AK: 3,
  AZ: 11,
  AR: 6,
  CA: 54,
  CO: 10,
  CT: 7,
  DE: 3,
  DC: 3,
  FL: 30,
  GA: 16,
  HI: 4,
  ID: 4,
  IL: 19,
  IN: 11,
  IA: 6,
  KS: 6,
  KY: 8,
  LA: 8,
  ME: 4,
  MD: 10,
  MA: 11,
  MI: 15,
  MN: 10,
  MS: 6,
  MO: 10,
  MT: 4,
  NE: 5,
  NV: 6,
  NH: 4,
  NJ: 14,
  NM: 5,
  NY: 28,
  NC: 16,
  ND: 3,
  OH: 17,
  OK: 7,
  OR: 8,
  PA: 19,
  RI: 4,
  SC: 9,
  SD: 3,
  TN: 11,
  TX: 40,
  UT: 6,
  VT: 3,
  VA: 13,
  WA: 12,
  WV: 4,
  WI: 10,
  WY: 3,
}

export const TOTAL_ELECTORAL_VOTES = Object.values(ELECTORAL_VOTES_BY_STATE).reduce((sum, votes) => sum + votes, 0)

export const MAJORITY_THRESHOLD = Math.floor(TOTAL_ELECTORAL_VOTES / 2) + 1

export const getElectoralVotes = (stateAbbr: string): number => ELECTORAL_VOTES_BY_STATE[stateAbbr] ?? 0
